---
- name: Set the index.html path
  set_fact:
    filepath: /var/www/html


- name: copy vars.html
  copy:
    src: vars.html
    dest: /var/www/html/vars.html
    owner: root
    group: root
    mode: 0755


- name: Add a link from index.html to vars.html
  lineinfile:
    path: /var/www/html/index.html
    line: <a href=vars.html> Ansible variable Page</a>
    insertafter: EOF
  ignore_errors: "{{ansible_check_mode}}"


- name: Insert hostname from ansible facts
  lineinfile:
    path: /var/www/html/vars.html
    line: <p> My name is {{ansible_host}}.</p>
    insertafter: EOF
  ignore_errors: "{{ansible_check_mode}}"


- name: Add a link from vars.html to index.html
  lineinfile:
    path: /var/www/html/vars.html
    line: <a href=vars.html> back to index.html</a>
    insertafter: EOF
  ignore_errors: "{{ansible_check_mode}}"


- name: Gather facts on a file
  stat:
    path: /etc/hosts
  register: i


- name: Insert aline when condition is true
  when: i.stat.exists == true
  lineinfile:
    path: /var/www/html/vars.html
    line: "<p>File {{i.stat.path}} exists.</p>"
  ignore_errors: "{{ansible_check_mode}}"


- name: set afact within a role
  set_fact:
    a_fact: The sky is green


- name: Insert a line using a_fact
  lineinfile:
    path: /var/www/html/vars.html
    line: "<p> {{a_fact}} </p>"
    insertafter: EOF
  ignore_errors: "{{ansible_check_mode}}"
