---
- name: Test the website
  hosts: webserver
  become: yes
  become_user: root

  tasks:
  - name: Check port 80 is listening on managed node
    wait_for:
      port: 80
      state: started
      timeout: 30  # Increase timeout to 30 seconds for better reliability

  - name: Verify apache is available remotely
    uri:
      url: http://{{ ansible_host }}/index.html
    delegate_to: localhost
    register: result
    failed_when: result.status != 200  # Fail the task if status code is not 200

  - name: Stat apache2 binary
    stat:
      path: /usr/sbin/apache2
    register: apache_stat

  - name: Fail if apache2 does not exist
    assert:
      that:
        - apache_stat.stat.exists
      fail_msg: "/usr/sbin/apache2 does not exist!"
      success_msg: "/usr/sbin/apache2 exists"

  - name: Verify apache2 is enabled
    shell: systemctl is-enabled apache2
    register: apache_enabled
    changed_when: false

  - name: Fail if apache2 is not enabled
    assert:
      that:
        - apache_enabled.stdout == 'enabled'
      fail_msg: "apache2 service is not enabled!"
      success_msg: "apache2 service is enabled"
  - name: Stat index.html
    stat:
      path: /var/www/html/index.html
    register: a
  - name: Confirm that index.html exist & owned by root
    assert:
      that: 
        - "a.stat.exists"
        - "a.stat.pw_name == 'root'"
      fail_msg: "index.html may not exist or have corrert ownership!"
      success_msg: "index.html exist with proper ownership"
